// AUTO-GENERATED by scripts/write-products-data.mjs. Re-run to refresh.
// Source: scraped from floorstoyouokc.com on 2026-05-18.

export type ProductCategory = {
  slug: string;
  service: string;
  label: string;
};

export type Product = {
  slug: string;
  name: string;
  category: string;
  service: string;
  image: string;
};

export const productCategories: ProductCategory[] = [
  {
    "slug": "carpet",
    "service": "carpet",
    "label": "Carpet"
  },
  {
    "slug": "engineered-wood",
    "service": "engineered-wood",
    "label": "Engineered Wood"
  },
  {
    "slug": "laminate",
    "service": "laminate",
    "label": "Laminate"
  },
  {
    "slug": "tile",
    "service": "tile",
    "label": "Tile"
  },
  {
    "slug": "vinyl-glue",
    "service": "vinyl-glue",
    "label": "Vinyl Glue (LVT)"
  },
  {
    "slug": "vinyl-click",
    "service": "vinyl-click",
    "label": "Vinyl Click (LVP / SPC)"
  }
];

export const products: Product[] = [
  {
    "slug": "all-the-rage",
    "name": "All The Rage",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/all-the-rage.webp"
  },
  {
    "slug": "big-city-acorn",
    "name": "Big City Acorn",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/big-city-acorn.webp"
  },
  {
    "slug": "big-city-frost",
    "name": "Big City Frost",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/big-city-frost.webp"
  },
  {
    "slug": "big-city-oxford",
    "name": "Big City Oxford",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/big-city-oxford.webp"
  },
  {
    "slug": "coast-battleship",
    "name": "Coast Battleship",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/coast-battleship.webp"
  },
  {
    "slug": "coast-bayside",
    "name": "Coast Bayside",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/coast-bayside.webp"
  },
  {
    "slug": "colored-i-granite",
    "name": "Colored I Granite",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/colored-i-granite.webp"
  },
  {
    "slug": "colored-i-magnetite",
    "name": "Colored I Magnetite",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/colored-i-magnetite.webp"
  },
  {
    "slug": "colored-i-sable",
    "name": "Colored I Sable",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/colored-i-sable.webp"
  },
  {
    "slug": "colored-i-shine",
    "name": "Colored I Shine",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/colored-i-shine.webp"
  },
  {
    "slug": "com-2-victory",
    "name": "Com 2 Victory",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/com-2-victory.webp"
  },
  {
    "slug": "com-misfit-charcoal",
    "name": "Com Misfit Charcoal",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/com-misfit-charcoal.webp"
  },
  {
    "slug": "cutting-edge-3644",
    "name": "Cutting Edge 3644",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/cutting-edge-3644.webp"
  },
  {
    "slug": "cw3-stonex",
    "name": "CW3 STONEX",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/cw3-stonex.webp"
  },
  {
    "slug": "determination-grey",
    "name": "Determination Grey",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/determination-grey.webp"
  },
  {
    "slug": "determination-red-wine",
    "name": "Determination Red Wine",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/determination-red-wine.webp"
  },
  {
    "slug": "everest-zebra",
    "name": "Everest Zebra",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/everest-zebra.webp"
  },
  {
    "slug": "expect-more",
    "name": "Expect More",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/expect-more.webp"
  },
  {
    "slug": "flutter-28",
    "name": "Flutter 28",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/flutter-28.webp"
  },
  {
    "slug": "graphix-brown-709",
    "name": "Graphix Brown 709",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/graphix-brown-709.webp"
  },
  {
    "slug": "graphix-green",
    "name": "Graphix Green",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/graphix-green.webp"
  },
  {
    "slug": "graphix-green-788",
    "name": "Graphix Green 788",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/graphix-green-788.webp"
  },
  {
    "slug": "graphix-lilac",
    "name": "Graphix Lilac",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/graphix-lilac.webp"
  },
  {
    "slug": "green-301",
    "name": "Green 301",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/green-301.webp"
  },
  {
    "slug": "herb-rattan",
    "name": "Herb Rattan",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/herb-rattan.webp"
  },
  {
    "slug": "hustle-boogie",
    "name": "Hustle Boogie",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/hustle-boogie.webp"
  },
  {
    "slug": "lets-go-210",
    "name": "Let’s Go 210",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/lets-go-210.webp"
  },
  {
    "slug": "lets-go-710",
    "name": "Let’s Go 710",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/lets-go-710.webp"
  },
  {
    "slug": "luxurious-shores",
    "name": "Luxurious Shores",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/luxurious-shores.webp"
  },
  {
    "slug": "magnify-1938-sp",
    "name": "Magnify 1938 SP",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/magnify-1938-sp.webp"
  },
  {
    "slug": "matador-2",
    "name": "Matador 2",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/matador-2.webp"
  },
  {
    "slug": "matador-64",
    "name": "Matador 64",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/matador-64.webp"
  },
  {
    "slug": "matador-chocolate",
    "name": "Matador Chocolate",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/matador-chocolate.webp"
  },
  {
    "slug": "matador-grey",
    "name": "Matador Grey",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/matador-grey.webp"
  },
  {
    "slug": "modern-sand",
    "name": "Modern Sand",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/modern-sand.webp"
  },
  {
    "slug": "modern-sky",
    "name": "Modern Sky",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/modern-sky.webp"
  },
  {
    "slug": "modern-stillwater",
    "name": "Modern Stillwater",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/modern-stillwater.webp"
  },
  {
    "slug": "moonstone-903",
    "name": "Moonstone 903",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/moonstone-903.webp"
  },
  {
    "slug": "multi-cotton",
    "name": "Multi Cotton",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/multi-cotton.webp"
  },
  {
    "slug": "multi-grey",
    "name": "Multi Grey",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/multi-grey.webp"
  },
  {
    "slug": "multi-rocky",
    "name": "Multi Rocky",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/multi-rocky.webp"
  },
  {
    "slug": "pinnacle-ii-chaparral",
    "name": "Pinnacle II Chaparral",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/pinnacle-ii-chaparral.webp"
  },
  {
    "slug": "shadow-979",
    "name": "Shadow 979",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/shadow-979.webp"
  },
  {
    "slug": "stonepeak-grey",
    "name": "Stonepeak Grey",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/stonepeak-grey.webp"
  },
  {
    "slug": "sycamore-grey",
    "name": "Sycamore Grey",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/sycamore-grey.webp"
  },
  {
    "slug": "tan-fleck",
    "name": "Tan Fleck",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/tan-fleck.webp"
  },
  {
    "slug": "thats-it-ashton",
    "name": "That’s It Ashton",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/thats-it-ashton.webp"
  },
  {
    "slug": "thats-it-charming",
    "name": "That’s It Charming",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/thats-it-charming.webp"
  },
  {
    "slug": "thats-it-ginger",
    "name": "That’s It Ginger",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/thats-it-ginger.webp"
  },
  {
    "slug": "thats-it-iron",
    "name": "That’s It Iron",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/thats-it-iron.webp"
  },
  {
    "slug": "xv575-smoke",
    "name": "XV575 Smoke",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/xv575-smoke.webp"
  },
  {
    "slug": "zinc-959",
    "name": "Zinc 959",
    "category": "carpet",
    "service": "carpet",
    "image": "/images/products/carpet/zinc-959.webp"
  },
  {
    "slug": "aerial-1445",
    "name": "Aerial 1445",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/aerial-1445.webp"
  },
  {
    "slug": "contour-1441",
    "name": "Contour 1441",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/contour-1441.webp"
  },
  {
    "slug": "corsica-circle",
    "name": "Corsica Circle",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/corsica-circle.webp"
  },
  {
    "slug": "flagstaff-hickory",
    "name": "Flagstaff Hickory",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/flagstaff-hickory.webp"
  },
  {
    "slug": "fresh-1443",
    "name": "Fresh 1443",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/fresh-1443.webp"
  },
  {
    "slug": "gun-powder-de175",
    "name": "Gun Powder DE175",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/gun-powder-de175.webp"
  },
  {
    "slug": "landmark-1440",
    "name": "Landmark 1440",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/landmark-1440.webp"
  },
  {
    "slug": "mosaic-1447",
    "name": "Mosaic 1447",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/mosaic-1447.webp"
  },
  {
    "slug": "peppered-oak",
    "name": "Peppered Oak",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/peppered-oak.webp"
  },
  {
    "slug": "roadshow-mocha",
    "name": "Roadshow Mocha",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/roadshow-mocha.webp"
  },
  {
    "slug": "sawmill-distressed",
    "name": "Sawmill Distressed",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/sawmill-distressed.webp"
  },
  {
    "slug": "true-north-1439",
    "name": "True North 1439",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/true-north-1439.webp"
  },
  {
    "slug": "windrush-stout",
    "name": "Windrush Stout",
    "category": "engineered-wood",
    "service": "engineered-wood",
    "image": "/images/products/engineered-wood/windrush-stout.webp"
  },
  {
    "slug": "angelica-natural-oak",
    "name": "Angelica Natural Oak",
    "category": "laminate",
    "service": "laminate",
    "image": "/images/products/laminate/angelica-natural-oak.webp"
  },
  {
    "slug": "byron-natural-oak",
    "name": "Byron Natural Oak",
    "category": "laminate",
    "service": "laminate",
    "image": "/images/products/laminate/byron-natural-oak.webp"
  },
  {
    "slug": "coventry-whispering-gray",
    "name": "Coventry Whispering Gray",
    "category": "laminate",
    "service": "laminate",
    "image": "/images/products/laminate/coventry-whispering-gray.webp"
  },
  {
    "slug": "dorado-zumi",
    "name": "Dorado Zumi",
    "category": "laminate",
    "service": "laminate",
    "image": "/images/products/laminate/dorado-zumi.webp"
  },
  {
    "slug": "margo-natural-walnut",
    "name": "Margo Natural Walnut",
    "category": "laminate",
    "service": "laminate",
    "image": "/images/products/laminate/margo-natural-walnut.webp"
  },
  {
    "slug": "valore-halifax",
    "name": "Valore Halifax",
    "category": "laminate",
    "service": "laminate",
    "image": "/images/products/laminate/valore-halifax.webp"
  },
  {
    "slug": "valore-madrid",
    "name": "Valore Madrid",
    "category": "laminate",
    "service": "laminate",
    "image": "/images/products/laminate/valore-madrid.webp"
  },
  {
    "slug": "a950-beige",
    "name": "A950 Beige",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/a950-beige.webp"
  },
  {
    "slug": "acazia-koa",
    "name": "Acazia Koa",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/acazia-koa.webp"
  },
  {
    "slug": "ao29-white",
    "name": "AO29 White",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/ao29-white.webp"
  },
  {
    "slug": "atacama-cinza",
    "name": "Atacama Cinza",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/atacama-cinza.webp"
  },
  {
    "slug": "baja-beige",
    "name": "Baja Beige",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/baja-beige.webp"
  },
  {
    "slug": "baja-beincut-beige",
    "name": "Baja Beincut Beige",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/baja-beincut-beige.webp"
  },
  {
    "slug": "baltic-brown",
    "name": "Baltic Brown",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/baltic-brown.webp"
  },
  {
    "slug": "bamboo-walnut",
    "name": "Bamboo Walnut",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/bamboo-walnut.webp"
  },
  {
    "slug": "black-galaxy",
    "name": "Black Galaxy",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/black-galaxy.webp"
  },
  {
    "slug": "black-metallic",
    "name": "Black Metallic",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/black-metallic.webp"
  },
  {
    "slug": "black-subway",
    "name": "Black Subway",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/black-subway.webp"
  },
  {
    "slug": "boulevard-paulista",
    "name": "Boulevard Paulista",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/boulevard-paulista.webp"
  },
  {
    "slug": "bridgeport-autumn",
    "name": "Bridgeport Autumn",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/bridgeport-autumn.webp"
  },
  {
    "slug": "bridgeport-summer",
    "name": "Bridgeport Summer",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/bridgeport-summer.webp"
  },
  {
    "slug": "brooklyn-ash",
    "name": "Brooklyn Ash",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/brooklyn-ash.webp"
  },
  {
    "slug": "brooklyn-gris",
    "name": "Brooklyn Gris",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/brooklyn-gris.webp"
  },
  {
    "slug": "brooklyn-oyster",
    "name": "Brooklyn Oyster",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/brooklyn-oyster.webp"
  },
  {
    "slug": "calacatta-white",
    "name": "Calacatta white",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/calacatta-white.webp"
  },
  {
    "slug": "carrara-1520-gray",
    "name": "Carrara #1520 Gray",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/carrara-1520-gray.webp"
  },
  {
    "slug": "classico-charcoal",
    "name": "Classico Charcoal",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/classico-charcoal.webp"
  },
  {
    "slug": "colonial-grey",
    "name": "Colonial Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/colonial-grey.webp"
  },
  {
    "slug": "component-riverwood",
    "name": "Component Riverwood",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/component-riverwood.webp"
  },
  {
    "slug": "component-westchester-grey",
    "name": "Component Westchester Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/component-westchester-grey.webp"
  },
  {
    "slug": "dapple-grey",
    "name": "Dapple Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/dapple-grey.webp"
  },
  {
    "slug": "duomo-bianchi",
    "name": "Duomo Bianchi",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/duomo-bianchi.webp"
  },
  {
    "slug": "et06-black",
    "name": "ET06 Black",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/et06-black.webp"
  },
  {
    "slug": "evening-grey",
    "name": "Evening Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/evening-grey.webp"
  },
  {
    "slug": "falesia-platina",
    "name": "Falesia Platina",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/falesia-platina.webp"
  },
  {
    "slug": "forest-burlap",
    "name": "Forest Burlap",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/forest-burlap.webp"
  },
  {
    "slug": "forest-cambrium",
    "name": "Forest Cambrium",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/forest-cambrium.webp"
  },
  {
    "slug": "future-black",
    "name": "Future Black",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/future-black.webp"
  },
  {
    "slug": "future-black1",
    "name": "Future Black(1)",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/future-black1.webp"
  },
  {
    "slug": "la-paz-blue-agave",
    "name": "La Paz Blue Agave",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/la-paz-blue-agave.webp"
  },
  {
    "slug": "lasa-beige",
    "name": "Lasa Beige",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/lasa-beige.webp"
  },
  {
    "slug": "light-brown",
    "name": "light brown",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/light-brown.webp"
  },
  {
    "slug": "lipstick-bombshell-red",
    "name": "Lipstick Bombshell Red",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/lipstick-bombshell-red.webp"
  },
  {
    "slug": "lucente-blanc",
    "name": "Lucente Blanc",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/lucente-blanc.webp"
  },
  {
    "slug": "midland-perspective-grey",
    "name": "Midland Perspective Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/midland-perspective-grey.webp"
  },
  {
    "slug": "mosaic-real-stone",
    "name": "Mosaic Real Stone",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/mosaic-real-stone.webp"
  },
  {
    "slug": "norway-bronze",
    "name": "Norway Bronze",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/norway-bronze.webp"
  },
  {
    "slug": "norway-brown",
    "name": "Norway Brown",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/norway-brown.webp"
  },
  {
    "slug": "norway-gold",
    "name": "Norway Gold",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/norway-gold.webp"
  },
  {
    "slug": "norway-grey",
    "name": "Norway Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/norway-grey.webp"
  },
  {
    "slug": "nutmeg-matte",
    "name": "Nutmeg Matte",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/nutmeg-matte.webp"
  },
  {
    "slug": "prince-beige",
    "name": "Prince Beige",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/prince-beige.webp"
  },
  {
    "slug": "prince-noce",
    "name": "Prince Noce",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/prince-noce.webp"
  },
  {
    "slug": "prince-white",
    "name": "Prince White",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/prince-white.webp"
  },
  {
    "slug": "pw10-natural",
    "name": "PW10 Natural",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/pw10-natural.webp"
  },
  {
    "slug": "railwood_-all-styles",
    "name": "Railwood_ All Styles",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/railwood_-all-styles.webp"
  },
  {
    "slug": "range-dusty-trail",
    "name": "Range Dusty Trail",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/range-dusty-trail.webp"
  },
  {
    "slug": "rankin-arviat",
    "name": "Rankin Arviat",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/rankin-arviat.webp"
  },
  {
    "slug": "rustic-brown",
    "name": "Rustic Brown",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/rustic-brown.webp"
  },
  {
    "slug": "takoma-canyon",
    "name": "Takoma Canyon",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/takoma-canyon.webp"
  },
  {
    "slug": "timberlake-brown",
    "name": "Timberlake Brown",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/timberlake-brown.webp"
  },
  {
    "slug": "trevi-bone-12x24",
    "name": "Trevi Bone 12X24",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/trevi-bone-12x24.webp"
  },
  {
    "slug": "trevi-bone-18x18",
    "name": "Trevi Bone 18X18",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/trevi-bone-18x18.webp"
  },
  {
    "slug": "trevi-grey-12x24",
    "name": "Trevi Grey 12X24",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/trevi-grey-12x24.webp"
  },
  {
    "slug": "trevi-grey-18x18",
    "name": "Trevi Grey 18X18",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/trevi-grey-18x18.webp"
  },
  {
    "slug": "trevi-noce-12x24",
    "name": "Trevi Noce 12X24",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/trevi-noce-12x24.webp"
  },
  {
    "slug": "trevi-noce-18x18",
    "name": "Trevi Noce 18X18",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/trevi-noce-18x18.webp"
  },
  {
    "slug": "turin-grigio",
    "name": "Turin Grigio",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/turin-grigio.webp"
  },
  {
    "slug": "umbria-savera",
    "name": "Umbria Savera",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/umbria-savera.webp"
  },
  {
    "slug": "venetian-gold",
    "name": "Venetian Gold",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/venetian-gold.webp"
  },
  {
    "slug": "white-jade",
    "name": "White Jade",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/white-jade.webp"
  },
  {
    "slug": "white-subway",
    "name": "White Subway",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/white-subway.webp"
  },
  {
    "slug": "wine-cellar-copper",
    "name": "Wine Cellar Copper",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/wine-cellar-copper.webp"
  },
  {
    "slug": "wine-cellar-grey",
    "name": "Wine Cellar Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/wine-cellar-grey.webp"
  },
  {
    "slug": "wine-cellar-slate",
    "name": "Wine Cellar Slate",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/wine-cellar-slate.webp"
  },
  {
    "slug": "winter-snow",
    "name": "Winter Snow",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/winter-snow.webp"
  },
  {
    "slug": "wl12-ashbark",
    "name": "WL12- ashbark",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/wl12-ashbark.webp"
  },
  {
    "slug": "zarci-grey",
    "name": "Zarci Grey",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/zarci-grey.webp"
  },
  {
    "slug": "zephyr-breeze",
    "name": "Zephyr Breeze",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/zephyr-breeze.webp"
  },
  {
    "slug": "zone-oro-13x17",
    "name": "Zone Oro 13X17",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/zone-oro-13x17.webp"
  },
  {
    "slug": "zone-oro-17x17",
    "name": "Zone Oro 17X17",
    "category": "tile",
    "service": "tile",
    "image": "/images/products/tile/zone-oro-17x17.webp"
  },
  {
    "slug": "brown-700",
    "name": "Brown 700",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/brown-700.webp"
  },
  {
    "slug": "calli-brown",
    "name": "Calli Brown",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/calli-brown.webp"
  },
  {
    "slug": "coral-pine",
    "name": "Coral Pine",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/coral-pine.webp"
  },
  {
    "slug": "craft-bronze",
    "name": "Craft Bronze",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/craft-bronze.webp"
  },
  {
    "slug": "espresso-oak",
    "name": "Espresso Oak",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/espresso-oak.webp"
  },
  {
    "slug": "forest-floor",
    "name": "Forest Floor",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/forest-floor.webp"
  },
  {
    "slug": "freemont-brown",
    "name": "Freemont Brown",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/freemont-brown.webp"
  },
  {
    "slug": "richland-charcoal",
    "name": "Richland Charcoal",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/richland-charcoal.webp"
  },
  {
    "slug": "richland-umber",
    "name": "Richland Umber",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/richland-umber.webp"
  },
  {
    "slug": "tokyo-delight",
    "name": "Tokyo Delight",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/tokyo-delight.webp"
  },
  {
    "slug": "wooden-bobbin",
    "name": "Wooden Bobbin",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/wooden-bobbin.webp"
  },
  {
    "slug": "wooden-cloth",
    "name": "Wooden Cloth",
    "category": "vinyl-glue",
    "service": "vinyl-glue",
    "image": "/images/products/vinyl-glue/wooden-cloth.webp"
  },
  {
    "slug": "berkley-spc",
    "name": "Berkley SPC",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/berkley-spc.webp"
  },
  {
    "slug": "blonde",
    "name": "Blonde",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/blonde.webp"
  },
  {
    "slug": "broce-76512by",
    "name": "Broce 76512BY",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/broce-76512by.webp"
  },
  {
    "slug": "brown-ash",
    "name": "Brown Ash",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/brown-ash.webp"
  },
  {
    "slug": "buff",
    "name": "Buff",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/buff.webp"
  },
  {
    "slug": "cape-651",
    "name": "Cape 651",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/cape-651.webp"
  },
  {
    "slug": "carrara-floating",
    "name": "Carrara Floating",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/carrara-floating.webp"
  },
  {
    "slug": "cedar-creek",
    "name": "Cedar Creek",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/cedar-creek.webp"
  },
  {
    "slug": "chickory",
    "name": "Chickory",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/chickory.webp"
  },
  {
    "slug": "clove",
    "name": "Clove",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/clove.webp"
  },
  {
    "slug": "desert-sand",
    "name": "Desert Sand",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/desert-sand.webp"
  },
  {
    "slug": "draven-wood",
    "name": "Draven Wood",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/draven-wood.webp"
  },
  {
    "slug": "earth",
    "name": "Earth",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/earth.webp"
  },
  {
    "slug": "impact-barnboard",
    "name": "Impact Barnboard",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/impact-barnboard.webp"
  },
  {
    "slug": "impact-weathered",
    "name": "Impact Weathered",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/impact-weathered.webp"
  },
  {
    "slug": "matrix",
    "name": "Matrix",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/matrix.webp"
  },
  {
    "slug": "middle-oak",
    "name": "Middle Oak",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/middle-oak.webp"
  },
  {
    "slug": "new-avenue",
    "name": "New Avenue",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/new-avenue.webp"
  },
  {
    "slug": "playa",
    "name": "Playa",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/playa.webp"
  },
  {
    "slug": "stylish-gray",
    "name": "Stylish Gray",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/stylish-gray.webp"
  },
  {
    "slug": "treasure-oak",
    "name": "Treasure Oak",
    "category": "vinyl-click",
    "service": "vinyl-click",
    "image": "/images/products/vinyl-click/treasure-oak.webp"
  }
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
export const productsByCategory = (cat: string) => products.filter((p) => p.category === cat);
export const productsByService = (service: string) => products.filter((p) => p.service === service);
